apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server-change-request
  namespace: default
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: server
#        image: harbor.middleware.com/shenkonghui/admission-controller-webhook-request:v0.4
        image: 10.10.102.124/shenkonghui/admission-controller-webhook-request:v0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: webhook-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server-change-request
  namespace: default
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server-change-request.default.svc
#    namespaceSelector:
#      matchExpressions:
#        - key: environment
#          operator: In
#          values: [ "prod","staging" ]
#    objectSelector:
#      matchLabels:
#        foo: bar
    clientConfig:
      service:
        name: webhook-server-change-request
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtRENDQW9DZ0F3SUJBZ0lVWXIvL2tSVFVkMDZocmhzMXk2RlRRTS9aU3RRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1h6RUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdNQ0Zwb1pVcHBZVzVuTVJFd0R3WURWUVFIREFoSQpZVzVuV21odmRURUxNQWtHQTFVRUNnd0NTRU14RERBS0JnTlZCQXNNQTBSbGRqRVBNQTBHQTFVRUF3d0dZMkV1ClkyOXRNQjRYRFRJeU1EWXpNREF6TkRBeU4xb1hEVEl6TURZek1EQXpOREF5TjFvd1h6RUxNQWtHQTFVRUJoTUMKUTA0eEVUQVBCZ05WQkFnTUNGcG9aVXBwWVc1bk1SRXdEd1lEVlFRSERBaElZVzVuV21odmRURUxNQWtHQTFVRQpDZ3dDU0VNeEREQUtCZ05WQkFzTUEwUmxkakVQTUEwR0ExVUVBd3dHWTJFdVkyOXRNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3aW1NYTd1RTh0M211blJ0cVpDS2w2a0dKbVdkSXIybkFMbnYKT2oycWlxOUN1SXpVR3pQZ0hwWXMvZkZTZHJkbFJXZmREMUx2R3MwWXcxeDhVTWpvQStmZzZhaDI0bUd2R1JUaQpac1VYb0pLNGkyWGFJL2YxakxNZC9oWWRGY2lMWEYyVWhINmVtd2RXVTVpMGFuWFN2U3ViS00wSUpEMnNFS1ZKCnlPTFpzcEVYVXRBTjNWZkxwUmROSHZtaTRaSitCcWtiaUNrSmRpQWZURFVrOFZGaFU5ZjFaU2k1aWliWGsrR2gKeGNZeU9GRURReVEwTVJ5ZXZjYm5nb2lRMmxVcGNEOGlwTC9OQlpkRm1uYll3YjJhSDdNVXJlZXNmclRoZUNVMgpjZkdoaWdSQ2R6ZkNRSmNwcEZTeWpQZ0x5SEE2dUZYdmxOaXB4dlJxQ3JHRTIxaE1Md0lEQVFBQm8wd3dTakFNCkJnTlZIUk1FQlRBREFRSC9NRG9HQTFVZEVRUXpNREdIQkg4QUFBR0NLWGRsWW1odmIyc3RjMlZ5ZG1WeUxXTm8KWVc1blpTMXlaWEYxWlhOMExtUmxabUYxYkhRdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNGWlVQWQpSMi9zL1VPa043V29JQWtmMmdONWNPelVWclBYdDdDaytkNklEeTFmZkdlSHBCbkhTSnFISml3Tmd1anhIa2JVCm92MjJNVnZhVmIvblRSV2xDM0JscEZQaTBRODFTa0tuVm9mY2tOZGNjaGR2RitVb2F1ZkFxdXpMYnMwc0dmQ2sKUktRUk9OV3ZIbHdiUnlBaUEyaTM1NjUybVJMZ1VIVEZsTW5XYWVTQUE4QURoc2NKSzQrUWFIZld2MWZlZy9nagpDb0hGWm5FSnhLOEtiYml0OXhiblE5OFN0cVBFQTVEREF1UFpWTE1CWWd6elR0QlVZU2xDTnh6dDhhZjVyK0VZCnBWK2xZYWZLVGZpb3VPLzR4ZUNSRFVRV3g2MjRTTzYra25lNnROdm85RmNkbWF0aUoxRStGNmgzc204SUEyTGEKSVRJY3Fhb1ViRDExN3EzVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
---
apiVersion: v1
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTakNDQWpLZ0F3SUJBZ0lVUm9GR1pYTzZLWjFGUi9YdXhXd0h5Y3lXMlZRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1h6RUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdNQ0Zwb1pVcHBZVzVuTVJFd0R3WURWUVFIREFoSQpZVzVuV21odmRURUxNQWtHQTFVRUNnd0NTRU14RERBS0JnTlZCQXNNQTBSbGRqRVBNQTBHQTFVRUF3d0dZMkV1ClkyOXRNQjRYRFRJeU1EWXpNREF6TkRBeU9Gb1hEVE0yTURNd09EQXpOREF5T0Zvd0VURVBNQTBHQTFVRUF3d0cKYzJWeWRtVnlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW9oLzVBREFYc20wdApaM0Z3bzR0S2ZXaTFvWWFaTnIzYThmeVVKY1FUTWZTVGt5a1p3MURBTTlueWlIWVByNDFhdFh2c0daMmZoZW5WClVacTFtL3dqRXJqcXloV29oZTdqT0hkOHFsbVg4RTNIWFl1SElOak9QV21Ib3dhWmQ0bHhaaTd1UDNLMnpBR2UKVnJuNnRieDdReStwbkd4VHFTQ09VVHFxMG9CMktpdE1zL2tQRFE0RHJCWW84UVl6SUYzZG5oK2NOU2RTQ1lDNQpLOUwvRTRNZ3VaMzEvQ2dtcnBVakgreUNocnBoVTlETlJZalU3YUx3TWJROS80VzNXRTBUYk10allzOUY3VnZGCk02bXJFbXNqdmxCVUt0dWZzaXJ3aFZ0WVpTUDBVOTFwdTZtU0RvOGhMUkI2R3czUURiL0UxZDBXa3ZxVWJkYi8KUDJRYlBLMkM0UUlEQVFBQm8wd3dTakFNQmdOVkhSTUVCVEFEQVFIL01Eb0dBMVVkRVFRek1ER0hCSDhBQUFHQwpLWGRsWW1odmIyc3RjMlZ5ZG1WeUxXTm9ZVzVuWlMxeVpYRjFaWE4wTG1SbFptRjFiSFF1YzNaak1BMEdDU3FHClNJYjNEUUVCQ3dVQUE0SUJBUUNiSkxyOUFrR0lTN3pyelcycnRiZXRQRzJVTVlRdnE0QzRaVFc5M2sxU05GMFMKc3JxSmhkci9mTTZXeTM4eU80RmNJc0RCeVdGako4REZ0aEZVZFNLQlV6TEQ0bENlUHBUTXAzNXk2bithWGowWQpzVnFLQ0kvd0lIb3N2czR3aUxOR0wwM214cG5mTUQ3Vm1rd2ozVU5iVVQzSFJlSStXQ0FVZHhlNmcxRGpaTmJGCitJajlmZXFPem50bmc0KzB5T0puRXJiNytJVWNBcWt0U0VHbmRtNUY0TEFzUHdYQk9ROWRJTjhkcHZYVkFKRmIKSTJBR3FwRUhPZjZXTjJJQTdxeitGLzFyaDdRK3FmOGVTckF3dDM0a0I3WjJSMWg2THN5aS9hRWloMmptNEIvWApweTYyZmNzbFJ2TGU0NTFVTVVaMWhGNVB4aTlxYzBLZlNDdXlkSXhjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBb2gvNUFEQVhzbTB0WjNGd280dEtmV2kxb1lhWk5yM2E4ZnlVSmNRVE1mU1RreWtaCncxREFNOW55aUhZUHI0MWF0WHZzR1oyZmhlblZVWnExbS93akVyanF5aFdvaGU3ak9IZDhxbG1YOEUzSFhZdUgKSU5qT1BXbUhvd2FaZDRseFppN3VQM0syekFHZVZybjZ0Yng3UXkrcG5HeFRxU0NPVVRxcTBvQjJLaXRNcy9rUApEUTREckJZbzhRWXpJRjNkbmgrY05TZFNDWUM1SzlML0U0TWd1WjMxL0NnbXJwVWpIK3lDaHJwaFU5RE5SWWpVCjdhTHdNYlE5LzRXM1dFMFRiTXRqWXM5RjdWdkZNNm1yRW1zanZsQlVLdHVmc2lyd2hWdFlaU1AwVTkxcHU2bVMKRG84aExSQjZHdzNRRGIvRTFkMFdrdnFVYmRiL1AyUWJQSzJDNFFJREFRQUJBb0lCQVFDWkhZY21OVVY4SHY1OQpycmFKenJpWVBuY2p5U0lVZ0RReXpMQUNCdTkyQTU0SW93MlEyRWZkOEozTllXc3BDbUE3L0lDY0pMQ1BZYXMwCitkOUJKVnplaHNRLy9UcCsyNEcvUjZIMnBNMEpoL3VkRG5TZGdnVXVIT2VjQVZTWmY3WVlvb1FpYWkzWCtFTloKZHlZZjA1VzZlMTQ5dkZVNjZ1TmVOZ0UwODF3bUwrTzcvYWFSeFZBZlNnVEFveTBCekZLT3A5U0FFUXF5eFNoRgpnalozS0QrcktldVBOaW1XT21LTzd3NFkyMklmYm93UzNRQnpsZXNJbGQyWkpDYlZQTHJjNndOaDZyOFczNU5aCjE2WFdLKy9ha2kxcWxYT1pYck9XRnFUK3B0cmxmbE1mZHIyRkRRYjgyYzRNQWJWM0dmRTFzcXltdUQ1UjF1TDQKUkV4ajdWSFJBb0dCQU5FamU5dzFieUtsVHpvSW04UFB1STFGdEZNWCtDT1dzVW5zaGZGalFpYU5Wc2pTNkt0NAowUmlmWFh2Kyt5VThrZnQyMGtWU3JuT1Y0Qk1CVEhGTVFWNytXZW1PaGljVXpHcXorYVZYTzluTmRFV1Y2dCtPCm5nc2t3ZHhncjVtVWtidnU5bUdVS3o0OXhtaSsrMmZFeFJubmFSSmZoY3RKWWZ2SlR0b0V2TzNOQW9HQkFNWnoKdFh2TjZmQzBKWkhaTlRXcXc3WldCTUc1czd6K1hubWZNRmwzcVY4Y2VkY0J4bGlMVmh3MURZU09RRUlyNmg2bApJeXI0RFRKdllSUHNGcGJEcThnTHhDWmZZVWgvVmFyU3NaZGRyWnB4VE1udzdTc0FuSzNteStQVnQ4bEJydXFhCnQyM0tvN0p6M2VDMlhlSkthYVlRbUw0emVqRDhUS2kwSFR3T1NYVmxBb0dBWW15N3J3QXF4SGhlRitiVFA4MHoKZ3JFS1U0elZTQkowYjJEMERJMTFKV1doTVRRcE1nSFREaTU2TlkvanJEdWNUR2M0UUUzUU1pK1gyL25oZXZTegpVenlMSGlMb09kNU04ZTZ2ajhQRk5CVEFJcnVTWlJIZWlVb01QbVgyWG1ZUVRBMERRUnNWV3Q2QjBPd0lyMlpvCmlHOWpBTFdaNXZrck51OGZ2L1U0NFFVQ2dZRUF3SGZ1VnNGeGwzS1FVWEN4QzNpdjBjS0JZSVhEalpQQ2V3QnEKT3dzMEtEdU02M3NjTERvTzdOS0Rac0UwRHpsYUdoaWRFQXA5ZWlITnJDMjRCc2FGYjBJQ0hoazVWNyt2alRwRQo1UUlFNGhucW1KeGkyT2NDRGlNZU1ielFQNC9Gbm1FcGI0RXQzR0JGbTdBalE5cFp0cWE0RFJnTjlUNXM5dDJnCjBPTW1XWVVDZ1lFQXVidFhCQk83bytIYk44K0EyWUsrSkdRTGMrb2w1cXpESy9RUkdHeUE3bTlPeUpGWm56TjMKamhCWWJ1UGd2ZVFUYmVXSVlWMHIzK1M2cFZ0TjNMbGpQNnZWaTF3VGNhMnNYUlNKYkw1S0NWSHZGcGxLSjY1eQp2RFhoczdNT3N5VFY2ektZMm83QTlDaWQ0bGtrbHFZbFJlUmVDYkRuQUljTTkyeDAvRHd5VDFVPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name:  webhook-server-tls
  namespace: default