apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      url: "https://10.10.136.50:8443/mutate"
#      service:
#        name: webhook-server
#        namespace: webhook-demo
#        path: "/mutate"
#      caBundle: ${CA_PEM_B64}
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtRENDQW9DZ0F3SUJBZ0lVZXgrYTRwRTR2L1VxTk9uN3IxTFhib0pXVmZjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1h6RUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdNQ0Zwb1pVcHBZVzVuTVJFd0R3WURWUVFIREFoSQpZVzVuV21odmRURUxNQWtHQTFVRUNnd0NTRU14RERBS0JnTlZCQXNNQTBSbGRqRVBNQTBHQTFVRUF3d0dZMkV1ClkyOXRNQjRYRFRJeU1EWXpNREEyTkRjME5sb1hEVEl6TURZek1EQTJORGMwTmxvd1h6RUxNQWtHQTFVRUJoTUMKUTA0eEVUQVBCZ05WQkFnTUNGcG9aVXBwWVc1bk1SRXdEd1lEVlFRSERBaElZVzVuV21odmRURUxNQWtHQTFVRQpDZ3dDU0VNeEREQUtCZ05WQkFzTUEwUmxkakVQTUEwR0ExVUVBd3dHWTJFdVkyOXRNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyWFJHbnBVUHA4cjFRNTJrVndRRmRkUWh4QzZnU0EzY1FZUTYKaUlLNG1ScGFkcWVBQkE0Z3FpYys5UXBneTNqMWhVTE9KM0pQaFRUd0Vvb0g4UGpnckZ5bXJMR3gySVEramMreAp2V2NOV1I2SkEvd1F3L1JERExPSGJKNCtiSFNJNHd6T0pXT1JOU3U2YXhaVG5GTHZUSmI1YW5PUTMyVWJHVUlOCjlpTXJZM3k0b0VkOC8wSzNuN0NuSXFteFJkZHBsT1BYbS8rMmVaTUl0NDZCVmxzQTlzeXkydjc5WXB2bWxvK3IKS3h2ODJaWEh0cVJaMlc3NUhZRG85NitaSnJsZnRBM2MxRFFpY21nZ0JFUm4xMnB5WkpDVFFDeHN4ZWMzanNFUAp1WUhSU3RGK1ZXNlN0VmJkNUVpbE9sRzdONnZ0UWdKQTlIaWVXNkpxb2JJcHBBQkViUUlEQVFBQm8wd3dTakFNCkJnTlZIUk1FQlRBREFRSC9NRG9HQTFVZEVRUXpNREdIQkFvS2lES0NLWGRsWW1odmIyc3RjMlZ5ZG1WeUxXTm8KWVc1blpTMXlaWEYxWlhOMExtUmxabUYxYkhRdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUM0VVFBYgpuK2VzOTVvTzVvRUpEeTZtalBMckVSbDBBL25uWGp1b3FvY1NmOFpYVGhTZzZuaVVoMFZpRVVTQzk0WnNvSkVlClhsTXFHem5ldFE5NjBYUEhoRG9vT0RpVld2Y0NYd3JnWEFwVktLK3FQRHNwb2JOWkY3UUtLUGNSV2dlRmthN3AKNWNjSXNSeHUvYlNoZHhIUEMybVFqdXhNb0VJTkFzdHo3L1RwSGk1TEtuNXFqcUZrK2xxQm94RW16RHRtbGkrcgpmWWhSSGx0blZGSC82REpQaTNmTFlWUlh4OUZFcWl6Sml2L0JETXNSQW9FWG9IeE9XaVBZU3JnaTRCTCtTNnozCkdaeUxUTWcvQXZDd0pVczlvQzNxVy9EbkEzcnNoTHFTZTJqM0kvN3gxeUljYjdUeUR6V05HQXd1akxXTmVkL3QKQ0xlVFdvUDl1b05NWFM3YgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE","UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]